name: bloc_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  google_fonts: ^6.2.1
  http: ^1.3.0
  hydrated_bloc: ^10.0.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  json_serializable: ^6.9.3
  bloc_test: ^10.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
